import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import { MantineProvider } from "@mantine/core";

import "@/app/globals.css";
import "@mantine/core/styles.css";
import Header from "@/components/HeaderComponent";
import CyberpunkBackground from "@/components/CyberpunkBackground";

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Movie Pulse",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: RootLayoutProps) {
  let messages;
  try {
    messages = (await import(`@/messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MantineProvider>
          <NextIntlClientProvider messages={messages}>
            <CyberpunkBackground />
            <Header locale={locale} />
            <main id="layout" className="flex flex-col">
              {children}
            </main>
          </NextIntlClientProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
